Catch the permission exception on the audio component
gradio-app/gradio pull request #2330
Opened 2022-09-24 14:52 UTC by Ian-GL

# Description

Currently the Audio component fails silently if the microphone permissions were not granted and the UI seems as if it was recording. This fix catches the permission exception and raises an alert that tells the user the permissions are needed. It also prevents the UI from showing the stop button as if it had started recording.

<img width="651" alt="Screen Shot 2022-09-24 at 9 51 50" src="https://user-images.githubusercontent.com/24900688/192104569-b1374286-085a-46a4-b216-9f60c4985138.png">

Closes: # (2325)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-26 15:31 UTC, abidlabs commented
Thanks @Ian-GL for the fix! This looks pretty good, but I wonder if it would be possible to use Gradio's Error instead of alert() for a better UI? cc @aliabid94

2022-09-26 17:29 UTC, Ian-GL commented
> Thanks @Ian-GL for the fix! This looks pretty good, but I wonder if it would be possible to use Gradio's Error instead of alert() for a better UI? cc @aliabid94

Hey @abidlabs , I wasn't aware of the error. Yes, if you have an example of another component that uses it I could use that as a guide to add it here.

2022-09-27 14:53 UTC, pngwn requested changes

2022-09-27 14:53 UTC, pngwn commented on ui/packages/audio/src/Audio.svelte
> +			});
We shouldn't be mixing await and `then` chaining. Lets wrap this in a `try` `catch` block instead.

Additionally should think of something less intrusive than an `alert` which blocks all interaction with the page? cc @gary149 @abidlabs

2022-09-28 05:54 UTC, aliabid94 commented
I'll make a PR against this fork to launch a gradio.Error from within a component - we don't have any examples of doing this before so I'll take care of that.

2022-09-29 04:01 UTC, aliabid94 commented
Just made the changes to use gradio error messaging, @pngwn please rereview

2022-09-29 14:15 UTC, pngwn commented
Pushed a change to convert the chained promises to `try` `catch` style, so we aren't mixing await + promise chaining, and fixed and issue with the type.

Looks good, thanks @Ian-GL and @aliabid94!

2022-09-29 14:15 UTC, pngwn approved these changes

2022-09-29 14:15 UTC, pngwn commented
Will merge when CI passes with everything merged in.

2022-09-29 14:33 UTC, merged

2022-09-29 15:55 UTC, Ian-GL commented
Thanks for taking care of the changes, @pngwn and @aliabid94 !