add argument to allow serving files from additional directories
gradio-app/gradio pull request #3075
Opened 2023-01-28 16:02 UTC by maxaudron

# Description

Add the `file_directories` argument to allow serving files from additional directories.
I was working on separating user data from source code for AUTOMATIC1111/stable-diffusion-webui to a directory external to the source and ran into trouble with various files the webui tries to serve from these locations.

# Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-01-30 18:13 UTC, abidlabs commented
Hi @maxaudron can you elaborate on the issue this PR is fixing a little more?

2023-01-31 11:17 UTC, maxaudron commented
@abidlabs I'm using nix to install stable-diffusion-webui as a proper python package, this is stored on a read-only filesystem, but really the same applies for any installed python packages as they should not be directly written to.

stable-diffusion-webui can for example use extensions that provide additional css or javascript files to serve. These are now stored outside the python app source, again, because read-only filesystem of the python app source, and just general good manners.

The source directory is also not necessarily the working directory, causing another potential detachment, I had worked around that by setting the working directory manually to the python app source.

It is a good security consideration to not allow serving from arbitrary directories, but serving files from outside the application's source has plenty of potential uses, and having an escape hatch to allow that is useful.

This way the application can provide a number of directories that are valid to serve files from, like it's own root based on the current file location, or any number of directories provided by configuration.

2023-01-31 22:41 UTC, abidlabs commented
Got it, thanks for the clarification. In the future, a better workflow would be to open an issue with the bug / feature request, so that the community and maintaining team can discuss the issue. But as a one off, I'll review this PR.

2023-01-31 23:16 UTC, abidlabs commented on gradio/blocks.py
> +        file_directories: List[str] = [],
Better to [avoid using a mutable as a default](https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/). Can you set this to be `None` and assign to it a list inside of the function?

2023-01-31 23:17 UTC, abidlabs commented on gradio/blocks.py
> +            file_directories: List of directories that gradio is allowed to serve files from. Must be absolute paths. Default []
```suggestion
            file_directories: List of directories that gradio is allowed to serve files from in addition to the directory containing the gradio script. Must be absolute paths.
```

2023-01-31 23:29 UTC, abidlabs commented on gradio/routes.py
> +            )
Can we do it this way to take advantage of pathlib's built-in `in` functionality
```suggestion
            in_file_dir = any((utils.abspath(dir) in utils.abspath(path).parents for dir in blocks.file_directories))
```

2023-01-31 23:33 UTC, abidlabs commented
Hi @maxaudron thanks again for the PR. I made some suggested changes to the PR. In addition, would you please be able to add a unit test that tests this functionality? You can see here for some similar tests: https://github.com/gradio-app/gradio/blob/4aa7d8d74b2d98f7c314e43a902983861d3d4dc9/test/test_routes.py#L183

2023-02-02 16:48 UTC, abidlabs requested changes
See above

2023-02-04 11:40 UTC, abidlabs commented
@maxaudron is this ready to be re-reviewed?

2023-02-04 16:43 UTC, maxaudron commented
@abidlabs yes, I've applied your suggestions and added a test

2023-02-06 01:34 UTC, abidlabs approved these changes

2023-02-06 01:40 UTC, abidlabs commented
Made a tweak to the test code, will merge in after it passes, thanks for the nice PR @maxaudron!

2023-02-06 02:04 UTC, merged