Dropdown Component Updates
gradio-app/gradio pull request #3211
Opened 2023-02-16 16:44 UTC by dawoodkhan82

# Description
Will include a few dropdown updates here:
Making the default dropdown use the custom dropdown UI
Adding A11y
Styling
Max_choices

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: # (issue)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

2023-02-21 12:10 UTC, pngwn requested changes
The design of this dropdown isn't consistent with the previous one. The font size is too large when typing into the box and the padding around the text is not consistent with the other form inputs. As a result the heights of this component don't match with the heights of the other 'input' components.

Compare the dropdown to the `Number` component at the top.

<img width="501" alt="Screenshot 2023-02-21 at 12 08 42" src="https://user-images.githubusercontent.com/12937446/220341037-b6dde262-f799-4e7f-b979-77fde6d43c6d.png">

2023-02-21 12:10 UTC, pngwn commented on ui/packages/form/src/Dropdown.svelte
>  <script lang="ts">
This file is getting too large. It needs to be broken down into smaller components, so it is easier to reason about.

2023-02-21 17:02 UTC, dawoodkhan82 commented
@pngwn I can update the text size and padding but didn't want to interfere with the changes being made here (https://github.com/gradio-app/gradio/issues/3163). But I guess I can make those changes myself in this PR

2023-02-21 18:45 UTC, pngwn commented
@dawoodkhan82 We can find another issue for that person. They are still having difficulties running the project locally.

2023-02-22 21:55 UTC, pngwn commented
@Neilblaze I'll be looking into your issue this week too. We don't want to discourage contributions because things are difficult to setup.

2023-02-22 21:59 UTC, dawoodkhan82 commented
@Neilblaze Will do!

2023-02-23 17:26 UTC, dawoodkhan82 commented
"flaky" backend tests are passing locally. Not sure what's going on

2023-02-23 17:56 UTC, freddyaboulton commented
I would ignore that failure @dawoodkhan82 !

2023-02-23 19:11 UTC, pngwn approved these changes
lgtm!

2023-02-23 19:32 UTC, dawoodkhan82 commented
@abidlabs mind taking a quick look?

2023-02-23 20:01 UTC, abidlabs commented on CHANGELOG.md
> +gr.Dropdown(label="Multiselect Dropdown", choices=CHOICES, multiselect=True, max_choices=2),
I would suggest just making this more of a complete example:

```suggestion
gr.Dropdown(label="Choose your favorite colors", choices=["red", "blue", "green", "yellow", "orange"], multiselect=True, max_choices=2),
```

2023-02-23 20:02 UTC, abidlabs commented on gradio/components.py
> +            warnings.warn("Max choices is ignored when multiselect is False.")
```suggestion
            warnings.warn("The `max_choices` parameter is ignored when `multiselect` is False.")
```

2023-02-23 20:06 UTC, abidlabs commented
Some documentation nits, but otherwise looks awesome @dawoodkhan82!

2023-02-23 20:06 UTC, abidlabs approved these changes

2023-02-23 21:32 UTC, merged