Only give same values .selected class in gr.Dropdown
gradio-app/gradio pull request #3644
Opened 2023-03-27 20:33 UTC by space-nuko

# Description

Closes: #3564

Still gives elements with the same value in the same dropdown the selected checkmark, unsure if this is desirable

<img width="318" alt="2023-03-27 16_32_01-Gradio - Chromium" src="https://user-images.githubusercontent.com/24979496/228059954-b9c82c61-f24a-48aa-81b9-ec403c2d8b83.png">

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-03-28 01:42 UTC, aliabid94 commented on js/form/src/DropdownOptions.svelte
> +				class:selected={value === choice}
```suggestion
				class:selected={Array.isArray(value) ? value.includes(choice) : value === choice}
```
So value can either be a single string, or an array of strings in multiselect mode. I believe this is why the original logic used "includes" to handle multiselect mode, but this suggestion should handle both cases.

2023-03-29 09:15 UTC, pngwn approved these changes
When we've fixed the changelog and run `pnpm format:write` to fix the formatting, i think this is good to go.

2023-03-29 19:46 UTC, pngwn requested changes
This should fix the TS error.

2023-03-29 19:46 UTC, pngwn commented on js/form/src/DropdownOptions.svelte
> +	function isSelected(choice) {
```suggestion
	function isSelected(choice: string) {
```

2023-03-29 22:10 UTC, pngwn approved these changes

2023-03-29 22:10 UTC, merged