Fix Httpx request UI timeout issue, time-consuming task waiting for 30 seconds
gradio-app/gradio pull request #4443
Opened 2023-06-07 07:05 UTC by Neokmi

Fix Httpx request UI timeout issue, time consuming task waiting for 30 seconds
#Description
During the use of multiple SD-WebUI plugins, strange errors are often thrown by the front-end UI after clicking the submit button After checking and debugging later, it was found that the error was caused by the last response result issued by "ws://localhost: 7860/queue/join" The code was located because the default timeout for httpx requests was too short, resulting in a response timeout But in reality, there are many backend tasks that are time-consuming (such as loading the model before processing the operation). Usually, it takes more than ten seconds, so the timeout must be set higher
I have completed multiple plugin tests on SD WebUI locally And they run well without any further errors, and even the 15 second processing task returns correct results without any errors
Please include:
*Relevant motivation
 Fix bugs and optimize user experience
*A summary of the change
 I'm not sure if it will cause other issues, such as long user waiting times
*Which issue is fixed
 Yes
*Any additional dependencies that are required for this change
 No need
Closes: # (issue)
#Checklist:
-[Y] I have performed a self review of my own code
-[Y] I have added a short summary of my change to the CHANGELOG.md
-[Y] My code follows the style guidelines of this project
-[Y] I have commented my code in hard to understand areas
-[Y] I have made corresponding changes to the documentation
-[Y] I have added tests that protect my fix is effective or that my feature works
-[Y] New and existing unit tests pass locally with my changes
#A note about the CHANGELOG
Hello 👋  And thank you for contributing to Graph!
All pull requests must update the change log located in CHANGELOG.md, less the pull request is labeled with the "no changelog update" label
Please add a brief summary of the change to the Upcoming Release>Full Changelog section of the CHANGELOG.md file and include
A link to the PR (formatted in markup) and a link to your github profile (if you like) For example, "* Added a cool new feature by ` [@ myusername] (link to your github profile) ` in ` [PR 11111]（ https://github.com/gradio-app/gradio/pull/11111 ）`
If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the
GitHub web UI since that lets you upload files directly via drag and drop. cuowu

2023-06-07 18:57 UTC, abidlabs commented on gradio/utils.py
> +            # Fix Httpx request UI timeout issue, time-consuming task waiting for 30 seconds
No need for this comment
```suggestion
```

2023-06-07 18:59 UTC, abidlabs commented on CHANGELOG.md
> +- Fix Httpx request UI timeout issue, time-consuming task waiting for 30 seconds
```suggestion
- Fix Httpx request timeout issue by waiting for 30 seconds by @Neokmi](https://github.com/neokmi) in [PR 4443](https://github.com/gradio-app/gradio/pull/4443).
```

2023-06-07 19:05 UTC, abidlabs commented
Hi @Neokmi when I test this locally, I get the following error:

<img width="639" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/2ff4d60f-8195-4b60-b8b9-b1c8eaaafe31">

I'm running `httpx` version 0.24.1 on MacOS. I see the same problem on Spaces here: https://huggingface.co/spaces/gradio-pr-deploys/pr-4443-all-demos

2023-06-07 19:10 UTC, abidlabs requested changes
See above

2023-06-07 23:49 UTC, Neokmi commented
Okay, mine is the Win11 system. I'll check it again

2023-06-08 00:38 UTC, Neokmi commented
> 见上文

My httpx version is 0.13.3, and the code on my end is supported.
It may be a compatibility issue with the httpx version However, in my httpx source code, the AsyncClient.send method found the timeout parameter. I need to debug the httpx code for this
<img width="559" alt="Snipaste_2023-06-08_08-18-31" src="https://github.com/gradio-app/gradio/assets/128426349/73849a69-f8a5-4b72-8622-89c8e281f1e4">
<img width="836" alt="Snipaste_2023-06-08_08-13-20" src="https://github.com/gradio-app/gradio/assets/128426349/b2787f64-39d0-4f7d-91a0-b5870fd5cd12">

According to official documentation, the default timeout for the client is 5 seconds, which is still too short

<img width="609" alt="Snipaste_2023-06-08_08-16-32" src="https://github.com/gradio-app/gradio/assets/128426349/c4e438df-0117-4eef-91e1-1e18c8ddce24">

This can cause communication errors in backend remote calls :
<img width="1240" alt="Snipaste_2023-06-07_14-33-13" src="https://github.com/gradio-app/gradio/assets/128426349/fe7fae87-0855-4e2d-8257-14613650ace1">



Perhaps setting a global timeout when initializing the AsyncClient client would be better

<img width="1149" alt="Snipaste_2023-06-08_08-10-41" src="https://github.com/gradio-app/gradio/assets/128426349/b9d8a3f7-6683-42d7-ae1a-dd9c7de8b95c">

2023-06-08 08:51 UTC, akx commented
According to [the changelog](https://github.com/encode/httpx/blob/master/CHANGELOG.md#0200-13th-october-2021), `client.send` does not accept `timeout=` since httpx 0.20.0, which was released in October 2021 (nearly 1 year 8 months ago).

The version you're using is over 3 years old.

I would maybe recommend changing the `httpx` dependency for `gradio` to `>=0.20.0`, and then changing this code to just always use `build_request` as recommended in the changelog there.

2023-06-08 11:49 UTC, Neokmi commented
Indeed, some frameworks mandate the use of older versions of httpx, but the new version of httpx.send does not support timeout settings Unless changed to another method setting Well, keep this suggestion for now because it is indeed a problem

2023-06-08 11:49 UTC, closed without merging

2023-06-08 12:02 UTC, akx commented
@Neokmi What frameworks are those? You should talk with their maintainers to allow a newer version than something 3 years old – who knows how many security issues have been fixed since!