Improve chatbot accessibility and UX
gradio-app/gradio pull request #5699
Opened 2023-09-26 22:22 UTC by hannahblair

## Description

This PR includes:
- improved HTML semantics specific to chatbots
- improved mobile UX
- new like/dislike icons - like + dislike is also filled when clicked
- allow switching between chatbot designs using `bubble` or `panel` via a new `layout` param

<img width="1297" alt="Screenshot 2023-09-27 at 14 29 26" src="https://github.com/gradio-app/gradio/assets/15165908/e0a24643-19a1-4da5-9797-0f0149c007fb">

<img width="506" alt="Screenshot 2023-09-27 at 16 44 32" src="https://github.com/gradio-app/gradio/assets/15165908/f305d51a-2775-4392-b377-a6848532ac43">

<img width="480" alt="Screenshot 2023-09-27 at 17 55 05" src="https://github.com/gradio-app/gradio/assets/15165908/ebc3c49a-a565-4f69-be9d-1d73563ea679">
<img width="1278" alt="Screenshot 2023-09-27 at 17 54 08" src="https://github.com/gradio-app/gradio/assets/15165908/3ec085e3-2f71-4a2b-b47a-e7153476db74">

demo: 

```
import gradio as gr

def test(x: gr.LikeData):
    print(x.index, x.value, x.liked)

with gr.Blocks() as demo:
    c = gr.Chatbot([["Donec id justo. Proin sapien ipsum, porta a, auctor quis, euismod ut, mi.", "Pellentesque libero tortor, tincidunt et, tincidunt eget, semper nec, quam. Aenean viverra rhoncus pede. Etiam sit amet orci eget eros faucibus tincidunt. In turpis.. Etiam iaculis nunc ac metus."], ["Phasellus viverra nulla ut metus varius laoreet. Duis lobortis massa imperdiet quam.", "Suspendisse potenti. Curabitur nisi. Sed lectus. Quisque malesuada placerat nisl. Vestibulum eu odio. Donec vitae orci sed dolor rutrum auctor. Fusce neque. Curabitur ligula sapien, tincidunt non, euismod vitae, posuere imperdiet, leo. Suspendisse feugiat."]], show_copy_button=True, layout="bubble")
    c.like(test, None, None)
    
demo.launch()
```

Closes: #5646 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

2023-09-29 14:53 UTC, dawoodkhan82 requested changes
Seems like the avatar image position changed

![Screenshot 2023-09-29 at 10 52 43 AM](https://github.com/gradio-app/gradio/assets/12725292/3cac6480-bb94-4d32-ad72-857eb1a8a212)

2023-09-29 14:58 UTC, dawoodkhan82 commented on js/chatbot/static/ChatBot.svelte
>  	}
Let's leave it the way it was before, and maybe we can add a param to customize it if devs request.

2023-09-29 14:58 UTC, dawoodkhan82 commented
The panel layout is clean! The copy button position seems a bit awkward to me tho.

![Screenshot 2023-09-29 at 10 56 28 AM](https://github.com/gradio-app/gradio/assets/12725292/7345f848-bf99-4470-8859-8ee4cea8ca60)

2023-09-29 15:05 UTC, dawoodkhan82 commented
The new button layouts for like and copy are super nice!

2023-10-02 15:18 UTC, dawoodkhan82 commented
Just tested everything, and it all looks and works great! One small nit is keeping the thumbs up/down button in a "clicked" UI state. So users know which messages they've liked when scrolling through the history.

2023-10-02 17:29 UTC, merged

2023-10-03 05:51 UTC, Keldos-Li commented
Wait, why use a `<button>` tag to wrap a message...? This doesn't align with the tag semantics at all😰! This is a huge disaster for downstream developers who need to adapt... 😢

I just don't understand... I think ordinary `<div>` can also contain the message information as well...?

2023-10-04 21:57 UTC, davies-w commented
How do I use this with ChatInterface?

2024-08-15 01:28 UTC, mardelden commented
@hannahblair , looks like someone broke your layout='panel' enhancement in 4.38.0 by introducing bubbles to the panel layout.