Allow passing height and width as string in `Blocks.svelte`
gradio-app/gradio pull request #6569
Opened 2023-11-24 11:17 UTC by hannahblair

## Description

Allows height and width to be passed as a string into `Blocks.svelte`, thus allowing height to be set as a percentage (or any unit available for height). This will apply to any components that accept `height` 👀 

Closes: #4966

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

2023-11-24 18:52 UTC, aliabid94 commented on js/atoms/src/Block.svelte
> +	style:height={getHeight()}
I don't believe this is reactive, e.g. if height changes this won't update. `height` should be an argument to this function to make it reactive

2023-11-24 19:01 UTC, aliabid94 commented
Didn't work for me:

```python
with gr.Blocks() as demo:
    name = gr.Chatbot(value=[["1", "2"]], height="100%")
    greet_btn = gr.Button("Test")
```

shows
<img width="933" alt="Screen Shot 2023-11-24 at 11 01 02 AM" src="https://github.com/gradio-app/gradio/assets/7870876/59a5ab26-0b9d-4d97-b265-0e499c7182ec">

Also I think it's somewhat unclear what the percentage would be relative to.

2023-12-07 16:24 UTC, abidlabs commented
> This should actually be documented for clarity. Maybe I'll update the Python docstring maybe? Open to thoughts

Agreed about documentation. It might be a lot to squeeze into the docstrings. What about adding a section in this Guide: https://www.gradio.app/guides/controlling-layout

2023-12-07 16:27 UTC, dawoodkhan82 requested changes

2023-12-07 16:27 UTC, dawoodkhan82 commented on gradio/components/chatbot.py
We should update ` height: int | None = None,` to include `string` type. Also should we update the other components that have a `height` param?

2023-12-08 10:45 UTC, pngwn approved these changes
I would echo @dawoodkhan82's comment about the docstrings but other than that looks great. Thanks @hannahblair!

2023-12-08 11:46 UTC, aliabid94 approved these changes
LGTM!

2023-12-11 12:33 UTC, pngwn approved these changes
Looks good, thanks for taking care of the improvements @hannahblair.

Feel free to dismiss the stale review and merge.

2023-12-11 14:25 UTC, pngwn reviewed
tweaks for formatting

2023-12-11 14:58 UTC, merged