Prevent components from working with non-uploaded files
gradio-app/gradio pull request #7465
Opened 2024-02-17 01:00 UTC by aliabid94

2024-02-18 19:59 UTC, freddyaboulton reviewed
I think we need to modify `run_fn_batch` to accept explicit_call (https://github.com/gradio-app/gradio/blob/cc51d9063043d896dbd219787c32e601f2fadd3e/gradio/blocks.py#L1532) and also this call to preprocess in the non batch case - https://github.com/gradio-app/gradio/blob/cc51d9063043d896dbd219787c32e601f2fadd3e/gradio/blocks.py#L1615

Otherwise looks good to me!

2024-02-19 08:01 UTC, akx requested changes

2024-02-19 08:01 UTC, akx commented on gradio/blocks.py
> +        explicit_call: bool = False,
New argument not documented?

2024-02-21 02:55 UTC, abidlabs commented on gradio/processing_utils.py
> +                assert path.startswith(get_upload_folder()), "File not in upload folder"
Use this function instead, its more robust:

https://vscode.dev/github/gradio-app/gradio/blob/revert/gradio/utils.py#L943

2024-02-21 02:56 UTC, abidlabs commented on gradio/processing_utils.py
> +        check_in_upload_folder: If True, instead of moving the file to cache, checks if the file is in upload folder.
Yes agree with @akx

2024-02-21 03:19 UTC, abidlabs commented on gradio/utils.py
> +def get_upload_folder():
Now that we have this function, we no longer need this attribute on the `Block` class. We can just use `utils.get_upload_folder()` everywhere this is used:

https://github.com/gradio-app/gradio/blob/99af290a9683f65e449b06a5e07572583ebcaaed/gradio/blocks.py#L122

2024-02-21 03:20 UTC, abidlabs commented on .changeset/moody-impalas-rule.md
> +"gradio": minor
Should be a patch version

2024-02-21 03:22 UTC, abidlabs commented on gradio/processing_utils.py
> +                assert path.startswith(get_upload_folder()), "File not in upload folder"
And maybe we can just `return` after this line (makes the logic easier to follow imo)

2024-02-21 03:22 UTC, abidlabs commented
Thanks @aliabid94! This should fix the issue. I would just add a unit test as well, and there's a few nits above.

2024-02-21 03:23 UTC, abidlabs approved these changes

2024-02-21 03:23 UTC, abidlabs commented on gradio/blocks.py
> +            explicit_call=True,
Nice catch

2024-02-21 20:02 UTC, PinkDraconian commented
This fix looks great. Thank you for the resolution. 
Would you also be able to "accept" my report? That way the process over there moves along.

2024-02-21 23:43 UTC, aliabid94 commented on gradio/processing_utils.py
> +                assert path.startswith(get_upload_folder()), "File not in upload folder"
> maybe we can just return after this line

I thought that the add_urls logic might still be needed, so I don't return early

2024-02-21 23:46 UTC, abidlabs commented on gradio/processing_utils.py
> +                assert path.startswith(get_upload_folder()), "File not in upload folder"
Oh you're right, I missed that.

2024-02-22 02:21 UTC, merged