Update test-functional.yml - Fix vulnerability code injection
gradio-app/gradio pull request #8145
Opened 2024-04-26 14:35 UTC by h2oa

## Description

Please include a concise summary, in clear English, of the changes in this pull request. If it closes an issue, please mention it here.

Closes: #(issue)

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

2024-04-26 17:27 UTC, pngwn requested changes
Thanks for this PR! Just left a small comment.

2024-04-26 17:27 UTC, pngwn commented on .github/workflows/test-functional.yml
We can actually just delete the offending `echo`, it is unused and a silly leftover from testing.

2024-04-30 20:22 UTC, freddyaboulton commented
Would love to merge this in @h2oa ! Can you make the small change @pngwn suggested ?

2024-05-01 13:48 UTC, freddyaboulton commented on .github/workflows/test-functional.yml
> +        env:
I think we can get rid of this entire step actually

2024-05-01 14:32 UTC, pngwn approved these changes
Thanks for this @h2oa!

2024-05-01 14:41 UTC, merged